### ISSUE TITLE
Support HiROMs.

### ISSUE THREAD

**Issue by AndreaOrru** [AndreaOrru/gilgamesh#1]

**Comment by LizardLad** [comment]
Are HiROMs supported by your decompiler as I tried to decompile Donkey Kong Country 2 - Diddy's Kong Quest and gilgamesh failed with the following error:


Traceback (most recent call last):
  File "gilgamesh.py", line 20, in <module>
    analyzer = Analyzer(database)
  File "/home/User/Development/Gilgamesh/gilgamesh/analyzer.py", line 28, in __init__
    self.analyze()
  File "/home/User/Development/Gilgamesh/gilgamesh/analyzer.py", line 32, in analyze
    self._labels = self.labels()
  File "/home/User/Development/Gilgamesh/gilgamesh/analyzer.py", line 128, in labels
    labels['sub_{:06X}'.format(subroutine)] = subroutine
  File "/usr/local/lib/python3.7/site-packages/bidict/_mut.py", line 80, in __setitem__
    self._put(key, val, on_dup)
  File "/usr/local/lib/python3.7/site-packages/bidict/_base.py", line 229, in _put
    dedup_result = self._dedup_item(key, val, on_dup)
  File "/usr/local/lib/python3.7/site-packages/bidict/_base.py", line 279, in _dedup_item
    raise ValueDuplicationError(val)
bidict._exc.ValueDuplicationError: 12181477

**Comment by AndreaOrru** [comment]
Haven't touched this code in a while, but I don't think they are ;)
